spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jshop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
  h2:
    console:
      enabled: true


mybatis:
  mapper-locations: classpath:mappers/*.xml  # Mapper XML 파일 위치 지정
  type-aliases-package: jbook.jshop.dto  # 도메인 클래스 위치 (선택 사항)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR